apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 533616270150.dkr.ecr.ap-northeast-2.amazonaws.com/react-frontend
  newName: 533616270150.dkr.ecr.ap-northeast-2.amazonaws.com/react-frontend
  newTag: 9874ba17
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
